create table if not exists public.items (
  id bigint generated by default as identity primary key,
  category text not null,
  name text not null,
  starting_stock numeric not null default 0,
  unit text not null,
  min_stock numeric not null default 0,
  physical_stock numeric null,
  created_at timestamptz not null default now()
);

create table if not exists public.stock_transactions (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.items(id) on delete cascade,
  date date not null,
  keluar numeric not null default 0,
  masuk numeric not null default 0,
  note text null,
  petugas text null,
  created_at timestamptz not null default now()
);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.items to anon, authenticated;
grant select, insert, update, delete on public.stock_transactions to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

alter table public.items enable row level security;
alter table public.stock_transactions enable row level security;

drop policy if exists "hf_items_select" on public.items;
drop policy if exists "hf_items_insert" on public.items;
drop policy if exists "hf_items_update" on public.items;
drop policy if exists "hf_items_delete" on public.items;
create policy "hf_items_select" on public.items for select using (true);
create policy "hf_items_insert" on public.items for insert with check (true);
create policy "hf_items_update" on public.items for update using (true) with check (true);
create policy "hf_items_delete" on public.items for delete using (true);

drop policy if exists "hf_tx_select" on public.stock_transactions;
drop policy if exists "hf_tx_insert" on public.stock_transactions;
drop policy if exists "hf_tx_update" on public.stock_transactions;
drop policy if exists "hf_tx_delete" on public.stock_transactions;
create policy "hf_tx_select" on public.stock_transactions for select using (true);
create policy "hf_tx_insert" on public.stock_transactions for insert with check (true);
create policy "hf_tx_update" on public.stock_transactions for update using (true) with check (true);
create policy "hf_tx_delete" on public.stock_transactions for delete using (true);

insert into public.items (id, category, name, starting_stock, unit, min_stock)
values
(1, 'Bahan Baku & Bumbu', 'Minyak', 54, 'Liters', 10),
(2, 'Bahan Baku & Bumbu', 'Dekstros', 28, 'kg', 10),
(3, 'Bahan Baku & Bumbu', 'Malto', 20, 'kg', 10),
(4, 'Bahan Baku & Bumbu', 'Citrun', 15, 'kg', 5),
(5, 'Bahan Baku & Bumbu', 'Garam', 25, 'kg', 10),
(6, 'Bahan Baku & Bumbu', 'Knorr', 4.7, 'kg', 2),
(7, 'Bahan Baku & Bumbu', 'Tepung Beras', 10.5, 'kg', 5),
(8, 'Bahan Baku & Bumbu', 'Tepung Jagung', 3.54, 'kg', 3),
(9, 'Bahan Baku & Bumbu', 'Tepung Kentang', 2.61, 'kg', 3),
(10, 'Bahan Baku & Bumbu', 'Baput (Bawang Putih)', 4, 'kg', 2),
(11, 'Bahan Baku & Bumbu', 'Garlic', 1, 'kg', 1),
(12, 'Bahan Baku & Bumbu', 'Lada Putih', 2.2, 'kg', 1),
(13, 'Bahan Baku & Bumbu', 'Keju C', 5.5, 'kg', 2),
(14, 'Bahan Baku & Bumbu', 'Keju M', 0, 'kg', 2),
(15, 'Bahan Baku & Bumbu', 'Baking Powder', 3, 'kg', 1),
(16, 'Bahan Baku & Bumbu', 'Paprika Bubuk', 3, 'kg', 1),
(17, 'Bahan Baku & Bumbu', 'Maizena', 14, 'kg', 5),
(18, 'Sayuran & Bahan Lain', 'Kentang', 0, 'kg', 50),
(19, 'Sayuran & Bahan Lain', 'Jagung', 25, 'kg', 10),
(20, 'Sayuran & Bahan Lain', 'Polong', 30, 'kg', 10),
(21, 'Sayuran & Bahan Lain', 'Meses', 93, 'Bungkus', 20),
(22, 'Sayuran & Bahan Lain', 'Edamame Kupas', 63, 'Bungkus', 20),
(23, 'Sayuran & Bahan Lain', 'Mix 3 Ways', 299, 'pcs', 50),
(24, 'Sayuran & Bahan Lain', 'Skin On 1 kg', 95, 'pcs', 30),
(25, 'Plastik & Kemasan', 'Southmount 2 kg', 0, 'pcs', 100),
(26, 'Plastik & Kemasan', 'HF 1 kg / 2 kg', 0, 'pcs', 100),
(27, 'Plastik & Kemasan', 'Polos 1 kg / 2 kg', 0, 'pcs', 100),
(28, 'Plastik & Kemasan', 'Southmount 500 tebal', 1826, 'pcs', 500),
(29, 'Plastik & Kemasan', 'Southmount 1 kg', 318, 'pcs', 300),
(30, 'Plastik & Kemasan', 'Plastik Bal / Kresek', 20, 'pcs', 50),
(31, 'Plastik & Kemasan', 'Plastik HF Baru 1 kg', 9291, 'pcs', 500),
(32, 'Stiker & Lakban', 'Lakban Bening', 5, 'Roll', 5),
(33, 'Stiker & Lakban', 'Stiker Ribon', 5, 'pcs', 5),
(34, 'Stiker & Lakban', 'Stiker Hijau T (Tua)', 5, 'pcs', 5),
(35, 'Stiker & Lakban', 'Stiker Biru T (Tua)', 3, 'pcs', 5),
(36, 'Stiker & Lakban', 'Stiker Ungu', 3, 'pcs', 5),
(37, 'Stiker & Lakban', 'Stiker Pink', 3, 'pcs', 5),
(38, 'Stiker & Lakban', 'Stiker Hitam', 1, 'pcs', 5),
(39, 'Stiker & Lakban', 'Stiker Orange', 3, 'pcs', 5),
(40, 'Stiker & Lakban', 'Stiker Kuning', 3, 'pcs', 5),
(41, 'Stiker & Lakban', 'Stiker Hijau S', 3, 'pcs', 5),
(42, 'Stiker & Lakban', 'Stiker Hijau J', 6, 'pcs', 5),
(43, 'Kebersihan & Perlengkapan', 'Sarung Tangan Plastik', 150, 'pcs', 100),
(44, 'Kebersihan & Perlengkapan', 'Sabun Lantai', 0, 'pcs', 5),
(45, 'Kebersihan & Perlengkapan', 'SOS', 0, 'pcs', 5)
on conflict (id) do update set
  category = excluded.category,
  name = excluded.name,
  starting_stock = excluded.starting_stock,
  unit = excluded.unit,
  min_stock = excluded.min_stock;

select setval(pg_get_serial_sequence('public.items', 'id'), coalesce((select max(id) from public.items), 1));
