-- Harry's Farm V88 - Ganti master item pakai KStok HF Maret Pabrik 2026
-- Total item sumber: 128
-- Aman untuk mengurangi item yang terlalu banyak:
-- item yang TIDAK ada di file KStok akan di-ARSIPKAN, bukan dihapus permanen.
-- Riwayat transaksi lama tetap aman.

alter table public.items
add column if not exists pcs_per_dus numeric not null default 0,
add column if not exists item_code text null,
add column if not exists archived boolean not null default false,
add column if not exists varian text null,
add column if not exists ukuran text null,
add column if not exists deskripsi text null,
add column if not exists lokasi text null,
add column if not exists supplier text null,
add column if not exists qc_status text not null default 'OK',
add column if not exists batch_lot text null,
add column if not exists expired_date date null;

create index if not exists idx_items_category on public.items (category);
create index if not exists idx_items_lokasi on public.items (lokasi);
create index if not exists idx_items_qc_status on public.items (qc_status);
create index if not exists idx_items_expired_date on public.items (expired_date);
create index if not exists idx_items_name_lower on public.items (lower(name));
create index if not exists idx_items_item_code on public.items (item_code);

with source_items(category, name, unit, starting_stock, min_stock, pcs_per_dus, item_code, lokasi, supplier, qc_status, deskripsi) as (
  values
('Produk Akhir', 'Wedges Plain 500gr', 'pcs', 0, 0, 20, 'PA01', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Wedges Plain 1kg', 'pcs', 0, 0, 10, 'PA02', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Wedges Plain 2kg', 'pcs', 0, 0, 5, 'PA03', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Waffle Seasoned Fries 500gr', 'pcs', 0, 0, 20, 'PA04', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Waffle Seasoned Fries 1kg', 'pcs', 0, 0, 10, 'PA05', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Waffle Seasoned Fries 2kg', 'pcs', 0, 0, 5, 'PA06', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Rendang Seasoned Wedges 500gr', 'pcs', 11, 0, 20, 'PA07', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Rendang Seasoned Wedges 1kg', 'pcs', 0, 0, 10, 'PA08', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Rendang Seasoned Wedges 2kg', 'pcs', 0, 0, 5, 'PA09', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 500gr', 'pcs', 37, 0, 20, 'PA10', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 1kg', 'pcs', -51, 0, 10, 'PA11', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 2kg', 'pcs', 0, 0, 5, 'PA12', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Cheesy Potato Nuggets 500gr', 'pcs', 0, 0, 20, 'PA13', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Cheesy Potato Nuggets 1kg', 'pcs', 11, 0, 10, 'PA14', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Cheesy Potato Nuggets 2kg', 'pcs', 0, 0, 5, 'PA15', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mozzarella Potato Sticks 10pcs', 'pcs', 0, 0, 0, 'PA16', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mozzarella Potato Balls 10pcs', 'pcs', 0, 0, 0, 'PA17', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mixed Vegetables 4 Ways 1kg', 'pcs', 4, 0, 10, 'PA18', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mixed Vegetables 3 Ways 1kg', 'pcs', 5, 0, 10, 'PA19', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mixed Capcay 1kg', 'pcs', 0, 0, 10, 'PA20', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Jagung Manis Pipil 1kg', 'pcs', 12, 0, 10, 'PA21', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Jagung', 'kg', 0, 0, 0, 'PA22', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Wortel', 'kg', 0, 0, 0, 'PA23', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Buncis', 'kg', 0, 0, 0, 'PA24', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Kacang Polong', 'kg', 0, 0, 0, 'PA25', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Crinkle Cut 500gr', 'pcs', 0, 0, 20, 'PA26', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Crinkle Cut 1kg', 'pcs', 0, 0, 10, 'PA27', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Crinkle Cut 2kg', 'pcs', 0, 0, 5, 'PA28', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 500gr', 'pcs', 0, 0, 20, 'PA29', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 1kg ( Sablon )', 'pcs', 30, 0, 10, 'PA30', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 2kg', 'pcs', 4, 0, 5, 'PA31', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Sweet Chopped Carrots', 'pcs', 0, 0, 0, 'PA32', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Shoestring Battercoated 2kg', 'kg', 0, 0, 5, 'PA33', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Baby Potato', 'pcs', 0, 0, 0, 'PA34', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Edamame 1kg', 'pcs', 0, 0, 10, 'PA35', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 1kg ( Polos )', 'pcs', 36, 0, 10, '', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 1kg ( Sablon ) GB', 'pcs', 0, 0, 10, '', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Bahan Baku', 'Kentang Atlantik', 'kg', 0, 0, 0, 'BB01', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kentang Granola', 'kg', 0, 0, 0, 'BB02', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kentang Medians', 'kg', 0, 0, 0, 'BB03', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Jagung', 'kg', 0, 0, 0, 'BB04', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Wortel', 'kg', 0, 0, 0, 'BB05', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Buncis', 'kg', 0, 0, 0, 'BB06', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kacang Polong', 'kg', 0, 0, 0, 'BB07', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Brokoli', 'kg', 0, 0, 0, 'BB08', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kembang Kol', 'kg', 0, 0, 0, 'BB09', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kentang Ventury', 'kg', 0, 0, 0, 'BB10', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Kemas', 'Plastik uk 30x45', 'pcs', 40939, 0, 0, 'BK01', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik uk 20x35', 'pcs', 149, 0, 0, 'BK02', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik uk 15x25', 'pcs', 0, 0, 0, 'BK03', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik uk 90x120 (trashbag)', 'pcs', 32, 0, 0, 'BK04', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Cheesy Potato Nugget 1kg', 'pcs', 45, 0, 0, 'BK05', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Cheesy Potato Nugget 250gr', 'pcs', 95, 0, 0, 'BK06', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Cheesy Potato Nugget 500gr (sablon)', 'pcs', 65, 0, 0, 'BK07', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Hashbrown 1kg', 'pcs', 180, 0, 0, 'BK08', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Hashbrown 250gr', 'pcs', 200, 0, 0, 'BK09', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Hashbrown 500gr', 'pcs', 0, 0, 0, 'BK10', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Jagung 500gr', 'pcs', 0, 0, 0, 'BK11', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Jagung 1kg', 'pcs', 480, 0, 0, 'BK12', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mashed Potato 1kg', 'pcs', 0, 0, 0, 'BK13', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mashed Potato 250gr', 'pcs', 66, 0, 0, 'BK14', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mashed Potato 500gr (sablon)', 'pcs', 0, 0, 0, 'BK15', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mix Vegetables 1kg', 'pcs', 45, 0, 0, 'BK16', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mix Vegetables 500gr', 'pcs', 47, 0, 0, 'BK17', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Polos 500gr', 'pcs', 22, 0, 0, 'BK18', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Polos 1kg', 'pcs', 215, 0, 0, 'BK19', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Polos 2kg', 'pcs', 4160, 0, 0, 'BK20', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Rendang Wedges 500gr (sablon)', 'pcs', 0, 0, 0, 'BK21', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Rendang Wedges 1kg', 'pcs', 0, 0, 0, 'BK22', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Fries 1kg', 'pcs', 0, 0, 0, 'BK23', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Fries 250gr', 'pcs', 0, 0, 0, 'BK24', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Fries 500gr', 'pcs', 0, 0, 0, 'BK25', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Wedges 1kg', 'pcs', 0, 0, 0, 'BK26', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Wedges 250gr', 'pcs', 0, 0, 0, 'BK27', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Wedges 500gr', 'pcs', 256, 0, 0, 'BK28', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Shoestring 1kg', 'pcs', 71, 0, 0, 'BK29', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Shoestring 500gr', 'pcs', 61, 0, 0, 'BK30', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Straightcut 1kg', 'pcs', 0, 0, 0, 'BK31', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Straightcut 500gr', 'pcs', 87, 0, 0, 'BK32', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Tulisan Hitam 1kg', 'pcs', 0, 0, 0, 'BK33', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Waffle Fries 500gr (sablon)', 'pcs', 396, 0, 0, 'BK34', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Waffle Fries 1kg', 'pcs', 0, 0, 0, 'BK35', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 1kg', 'pcs', 20, 0, 0, 'BK36', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 250gr', 'pcs', 57, 0, 0, 'BK37', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 500gr', 'pcs', 234, 0, 0, 'BK38', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 2kg', 'pcs', 40, 0, 0, 'BK39', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Stiker Potato Balls', 'pcs', 0, 0, 0, 'BK40', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Stiker Potato Sticks', 'pcs', 0, 0, 0, 'BK41', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Kardus Polos', 'pcs', 95, 0, 0, 'BK42', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Kardus Sablon', 'pcs', -35, 0, 0, 'BK43', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Lakban', 'roll', 3, 0, 0, 'BK44', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'plastik 60 x 100', 'pcs', 0, 0, 0, 'BK45', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Southmount 1kg', 'pcs', 560, 0, 0, 'BK46', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Southmount 2kg', 'pcs', 411, 0, 0, 'BK47', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'plastik 40 x 60', 'pcs', 0, 0, 0, 'BK48', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Crinkle Cut 1kg', 'pcs', 19, 0, 0, 'BK49', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Penolong', 'Masker', 'pcs', -58, 0, 0, 'BP01', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sarung Tangan Plastik', 'pcs', -275, 0, 0, 'BP02', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sarung Tangan Latex', 'pcs', 0, 0, 0, 'BP03', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Nurse Cap', 'pcs', -46, 0, 0, 'BP04', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Spidol', 'pcs', 12, 0, 0, 'BP05', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sabun Cuci Piring', 'ml', 570, 0, 0, 'BP06', 'Kebersihan & Sanitasi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sabun Lantai', 'pcs', 0, 0, 0, 'BP07', 'Kebersihan & Sanitasi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Tambahan Pangan', 'Minyak Sawit', 'liter', 0, 0, 0, 'BTP01', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Minyak Canola', 'liter', 5, 0, 0, 'BTP02', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Dextrose Monohydrate', 'gr', 2150, 0, 0, 'BTP03', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Malto Dextrin', 'gr', 18700, 0, 0, 'BTP04', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Citric Acid', 'gr', 24645, 0, 0, 'BTP05', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Garam', 'gr', 4600, 0, 0, 'BTP06', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Knorr', 'gr', 7710, 0, 0, 'BTP07', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Beras', 'gr', 54800, 0, 0, 'BTP08', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Terigu', 'gr', 0, 0, 0, 'BTP09', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Jagung', 'gr', 3540, 0, 0, 'BTP10', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Kentang', 'gr', 2610, 0, 0, 'BTP11', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Bawang Putih Bubuk / Garlic Powder', 'gr', 28565, 0, 0, 'BTP12', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Roasted Garlic', 'gr', 1000, 0, 0, 'BTP13', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Lada Putih', 'gr', 2765, 0, 0, 'BTP14', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Bumbu Rendang Indofood', 'pcs', 27, 0, 0, 'BTP15', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Keju Mozzarella', 'gr', 0, 0, 0, 'BTP16', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Keju Cheddar', 'gr', 6500, 0, 0, 'BTP17', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Polenta', 'gr', 0, 0, 0, 'BTP18', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Baking Powder', 'gr', 5530, 0, 0, 'BTP19', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Ragi', 'gr', 0, 0, 0, 'BTP20', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Chili Powder', 'gr', 0, 0, 0, 'BTP21', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Paprika Bubuk', 'gr', 15430, 0, 0, 'BTP22', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Pewarna Merah', 'ml', 0, 0, 0, 'BTP23', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Maizena', 'gr', 52950, 0, 0, 'BTP24', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tapioka', 'gr', 1000, 0, 0, 'BTP25', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan')
),
matched_source as (
  select s.*
  from source_items s
)
-- 1) Arsipkan item lama yang tidak ada di file KStok.
update public.items i
set archived = true
where coalesce(i.archived,false) = false
  and not exists (
    select 1
    from matched_source s
    where (nullif(s.item_code,'') is not null and nullif(i.item_code,'') = nullif(s.item_code,''))
       or (lower(trim(i.name)) = lower(trim(s.name)) and lower(trim(i.category)) = lower(trim(s.category)))
  );

with source_items(category, name, unit, starting_stock, min_stock, pcs_per_dus, item_code, lokasi, supplier, qc_status, deskripsi) as (
  values
('Produk Akhir', 'Wedges Plain 500gr', 'pcs', 0, 0, 20, 'PA01', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Wedges Plain 1kg', 'pcs', 0, 0, 10, 'PA02', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Wedges Plain 2kg', 'pcs', 0, 0, 5, 'PA03', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Waffle Seasoned Fries 500gr', 'pcs', 0, 0, 20, 'PA04', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Waffle Seasoned Fries 1kg', 'pcs', 0, 0, 10, 'PA05', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Waffle Seasoned Fries 2kg', 'pcs', 0, 0, 5, 'PA06', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Rendang Seasoned Wedges 500gr', 'pcs', 11, 0, 20, 'PA07', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Rendang Seasoned Wedges 1kg', 'pcs', 0, 0, 10, 'PA08', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Rendang Seasoned Wedges 2kg', 'pcs', 0, 0, 5, 'PA09', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 500gr', 'pcs', 37, 0, 20, 'PA10', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 1kg', 'pcs', -51, 0, 10, 'PA11', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 2kg', 'pcs', 0, 0, 5, 'PA12', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Cheesy Potato Nuggets 500gr', 'pcs', 0, 0, 20, 'PA13', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Cheesy Potato Nuggets 1kg', 'pcs', 11, 0, 10, 'PA14', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Cheesy Potato Nuggets 2kg', 'pcs', 0, 0, 5, 'PA15', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mozzarella Potato Sticks 10pcs', 'pcs', 0, 0, 0, 'PA16', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mozzarella Potato Balls 10pcs', 'pcs', 0, 0, 0, 'PA17', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mixed Vegetables 4 Ways 1kg', 'pcs', 4, 0, 10, 'PA18', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mixed Vegetables 3 Ways 1kg', 'pcs', 5, 0, 10, 'PA19', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mixed Capcay 1kg', 'pcs', 0, 0, 10, 'PA20', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Jagung Manis Pipil 1kg', 'pcs', 12, 0, 10, 'PA21', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Jagung', 'kg', 0, 0, 0, 'PA22', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Wortel', 'kg', 0, 0, 0, 'PA23', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Buncis', 'kg', 0, 0, 0, 'PA24', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Kacang Polong', 'kg', 0, 0, 0, 'PA25', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Crinkle Cut 500gr', 'pcs', 0, 0, 20, 'PA26', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Crinkle Cut 1kg', 'pcs', 0, 0, 10, 'PA27', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Crinkle Cut 2kg', 'pcs', 0, 0, 5, 'PA28', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 500gr', 'pcs', 0, 0, 20, 'PA29', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 1kg ( Sablon )', 'pcs', 30, 0, 10, 'PA30', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 2kg', 'pcs', 4, 0, 5, 'PA31', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Sweet Chopped Carrots', 'pcs', 0, 0, 0, 'PA32', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Shoestring Battercoated 2kg', 'kg', 0, 0, 5, 'PA33', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Baby Potato', 'pcs', 0, 0, 0, 'PA34', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Edamame 1kg', 'pcs', 0, 0, 10, 'PA35', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 1kg ( Polos )', 'pcs', 36, 0, 10, '', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 1kg ( Sablon ) GB', 'pcs', 0, 0, 10, '', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Bahan Baku', 'Kentang Atlantik', 'kg', 0, 0, 0, 'BB01', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kentang Granola', 'kg', 0, 0, 0, 'BB02', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kentang Medians', 'kg', 0, 0, 0, 'BB03', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Jagung', 'kg', 0, 0, 0, 'BB04', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Wortel', 'kg', 0, 0, 0, 'BB05', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Buncis', 'kg', 0, 0, 0, 'BB06', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kacang Polong', 'kg', 0, 0, 0, 'BB07', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Brokoli', 'kg', 0, 0, 0, 'BB08', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kembang Kol', 'kg', 0, 0, 0, 'BB09', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kentang Ventury', 'kg', 0, 0, 0, 'BB10', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Kemas', 'Plastik uk 30x45', 'pcs', 40939, 0, 0, 'BK01', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik uk 20x35', 'pcs', 149, 0, 0, 'BK02', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik uk 15x25', 'pcs', 0, 0, 0, 'BK03', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik uk 90x120 (trashbag)', 'pcs', 32, 0, 0, 'BK04', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Cheesy Potato Nugget 1kg', 'pcs', 45, 0, 0, 'BK05', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Cheesy Potato Nugget 250gr', 'pcs', 95, 0, 0, 'BK06', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Cheesy Potato Nugget 500gr (sablon)', 'pcs', 65, 0, 0, 'BK07', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Hashbrown 1kg', 'pcs', 180, 0, 0, 'BK08', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Hashbrown 250gr', 'pcs', 200, 0, 0, 'BK09', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Hashbrown 500gr', 'pcs', 0, 0, 0, 'BK10', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Jagung 500gr', 'pcs', 0, 0, 0, 'BK11', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Jagung 1kg', 'pcs', 480, 0, 0, 'BK12', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mashed Potato 1kg', 'pcs', 0, 0, 0, 'BK13', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mashed Potato 250gr', 'pcs', 66, 0, 0, 'BK14', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mashed Potato 500gr (sablon)', 'pcs', 0, 0, 0, 'BK15', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mix Vegetables 1kg', 'pcs', 45, 0, 0, 'BK16', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mix Vegetables 500gr', 'pcs', 47, 0, 0, 'BK17', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Polos 500gr', 'pcs', 22, 0, 0, 'BK18', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Polos 1kg', 'pcs', 215, 0, 0, 'BK19', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Polos 2kg', 'pcs', 4160, 0, 0, 'BK20', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Rendang Wedges 500gr (sablon)', 'pcs', 0, 0, 0, 'BK21', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Rendang Wedges 1kg', 'pcs', 0, 0, 0, 'BK22', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Fries 1kg', 'pcs', 0, 0, 0, 'BK23', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Fries 250gr', 'pcs', 0, 0, 0, 'BK24', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Fries 500gr', 'pcs', 0, 0, 0, 'BK25', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Wedges 1kg', 'pcs', 0, 0, 0, 'BK26', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Wedges 250gr', 'pcs', 0, 0, 0, 'BK27', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Wedges 500gr', 'pcs', 256, 0, 0, 'BK28', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Shoestring 1kg', 'pcs', 71, 0, 0, 'BK29', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Shoestring 500gr', 'pcs', 61, 0, 0, 'BK30', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Straightcut 1kg', 'pcs', 0, 0, 0, 'BK31', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Straightcut 500gr', 'pcs', 87, 0, 0, 'BK32', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Tulisan Hitam 1kg', 'pcs', 0, 0, 0, 'BK33', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Waffle Fries 500gr (sablon)', 'pcs', 396, 0, 0, 'BK34', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Waffle Fries 1kg', 'pcs', 0, 0, 0, 'BK35', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 1kg', 'pcs', 20, 0, 0, 'BK36', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 250gr', 'pcs', 57, 0, 0, 'BK37', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 500gr', 'pcs', 234, 0, 0, 'BK38', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 2kg', 'pcs', 40, 0, 0, 'BK39', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Stiker Potato Balls', 'pcs', 0, 0, 0, 'BK40', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Stiker Potato Sticks', 'pcs', 0, 0, 0, 'BK41', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Kardus Polos', 'pcs', 95, 0, 0, 'BK42', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Kardus Sablon', 'pcs', -35, 0, 0, 'BK43', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Lakban', 'roll', 3, 0, 0, 'BK44', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'plastik 60 x 100', 'pcs', 0, 0, 0, 'BK45', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Southmount 1kg', 'pcs', 560, 0, 0, 'BK46', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Southmount 2kg', 'pcs', 411, 0, 0, 'BK47', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'plastik 40 x 60', 'pcs', 0, 0, 0, 'BK48', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Crinkle Cut 1kg', 'pcs', 19, 0, 0, 'BK49', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Penolong', 'Masker', 'pcs', -58, 0, 0, 'BP01', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sarung Tangan Plastik', 'pcs', -275, 0, 0, 'BP02', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sarung Tangan Latex', 'pcs', 0, 0, 0, 'BP03', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Nurse Cap', 'pcs', -46, 0, 0, 'BP04', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Spidol', 'pcs', 12, 0, 0, 'BP05', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sabun Cuci Piring', 'ml', 570, 0, 0, 'BP06', 'Kebersihan & Sanitasi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sabun Lantai', 'pcs', 0, 0, 0, 'BP07', 'Kebersihan & Sanitasi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Tambahan Pangan', 'Minyak Sawit', 'liter', 0, 0, 0, 'BTP01', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Minyak Canola', 'liter', 5, 0, 0, 'BTP02', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Dextrose Monohydrate', 'gr', 2150, 0, 0, 'BTP03', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Malto Dextrin', 'gr', 18700, 0, 0, 'BTP04', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Citric Acid', 'gr', 24645, 0, 0, 'BTP05', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Garam', 'gr', 4600, 0, 0, 'BTP06', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Knorr', 'gr', 7710, 0, 0, 'BTP07', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Beras', 'gr', 54800, 0, 0, 'BTP08', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Terigu', 'gr', 0, 0, 0, 'BTP09', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Jagung', 'gr', 3540, 0, 0, 'BTP10', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Kentang', 'gr', 2610, 0, 0, 'BTP11', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Bawang Putih Bubuk / Garlic Powder', 'gr', 28565, 0, 0, 'BTP12', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Roasted Garlic', 'gr', 1000, 0, 0, 'BTP13', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Lada Putih', 'gr', 2765, 0, 0, 'BTP14', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Bumbu Rendang Indofood', 'pcs', 27, 0, 0, 'BTP15', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Keju Mozzarella', 'gr', 0, 0, 0, 'BTP16', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Keju Cheddar', 'gr', 6500, 0, 0, 'BTP17', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Polenta', 'gr', 0, 0, 0, 'BTP18', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Baking Powder', 'gr', 5530, 0, 0, 'BTP19', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Ragi', 'gr', 0, 0, 0, 'BTP20', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Chili Powder', 'gr', 0, 0, 0, 'BTP21', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Paprika Bubuk', 'gr', 15430, 0, 0, 'BTP22', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Pewarna Merah', 'ml', 0, 0, 0, 'BTP23', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Maizena', 'gr', 52950, 0, 0, 'BTP24', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tapioka', 'gr', 1000, 0, 0, 'BTP25', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan')
)
-- 2) Update item yang ketemu berdasarkan kode.
update public.items i
set
  category = s.category,
  name = s.name,
  unit = s.unit,
  min_stock = s.min_stock,
  pcs_per_dus = s.pcs_per_dus,
  item_code = nullif(s.item_code,''),
  lokasi = s.lokasi,
  supplier = s.supplier,
  qc_status = s.qc_status,
  deskripsi = s.deskripsi,
  archived = false
from source_items s
where nullif(s.item_code,'') is not null
  and nullif(i.item_code,'') = nullif(s.item_code,'');

with source_items(category, name, unit, starting_stock, min_stock, pcs_per_dus, item_code, lokasi, supplier, qc_status, deskripsi) as (
  values
('Produk Akhir', 'Wedges Plain 500gr', 'pcs', 0, 0, 20, 'PA01', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Wedges Plain 1kg', 'pcs', 0, 0, 10, 'PA02', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Wedges Plain 2kg', 'pcs', 0, 0, 5, 'PA03', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Waffle Seasoned Fries 500gr', 'pcs', 0, 0, 20, 'PA04', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Waffle Seasoned Fries 1kg', 'pcs', 0, 0, 10, 'PA05', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Waffle Seasoned Fries 2kg', 'pcs', 0, 0, 5, 'PA06', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Rendang Seasoned Wedges 500gr', 'pcs', 11, 0, 20, 'PA07', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Rendang Seasoned Wedges 1kg', 'pcs', 0, 0, 10, 'PA08', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Rendang Seasoned Wedges 2kg', 'pcs', 0, 0, 5, 'PA09', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 500gr', 'pcs', 37, 0, 20, 'PA10', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 1kg', 'pcs', -51, 0, 10, 'PA11', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 2kg', 'pcs', 0, 0, 5, 'PA12', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Cheesy Potato Nuggets 500gr', 'pcs', 0, 0, 20, 'PA13', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Cheesy Potato Nuggets 1kg', 'pcs', 11, 0, 10, 'PA14', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Cheesy Potato Nuggets 2kg', 'pcs', 0, 0, 5, 'PA15', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mozzarella Potato Sticks 10pcs', 'pcs', 0, 0, 0, 'PA16', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mozzarella Potato Balls 10pcs', 'pcs', 0, 0, 0, 'PA17', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mixed Vegetables 4 Ways 1kg', 'pcs', 4, 0, 10, 'PA18', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mixed Vegetables 3 Ways 1kg', 'pcs', 5, 0, 10, 'PA19', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mixed Capcay 1kg', 'pcs', 0, 0, 10, 'PA20', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Jagung Manis Pipil 1kg', 'pcs', 12, 0, 10, 'PA21', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Jagung', 'kg', 0, 0, 0, 'PA22', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Wortel', 'kg', 0, 0, 0, 'PA23', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Buncis', 'kg', 0, 0, 0, 'PA24', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Kacang Polong', 'kg', 0, 0, 0, 'PA25', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Crinkle Cut 500gr', 'pcs', 0, 0, 20, 'PA26', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Crinkle Cut 1kg', 'pcs', 0, 0, 10, 'PA27', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Crinkle Cut 2kg', 'pcs', 0, 0, 5, 'PA28', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 500gr', 'pcs', 0, 0, 20, 'PA29', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 1kg ( Sablon )', 'pcs', 30, 0, 10, 'PA30', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 2kg', 'pcs', 4, 0, 5, 'PA31', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Sweet Chopped Carrots', 'pcs', 0, 0, 0, 'PA32', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Shoestring Battercoated 2kg', 'kg', 0, 0, 5, 'PA33', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Baby Potato', 'pcs', 0, 0, 0, 'PA34', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Edamame 1kg', 'pcs', 0, 0, 10, 'PA35', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 1kg ( Polos )', 'pcs', 36, 0, 10, '', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 1kg ( Sablon ) GB', 'pcs', 0, 0, 10, '', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Bahan Baku', 'Kentang Atlantik', 'kg', 0, 0, 0, 'BB01', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kentang Granola', 'kg', 0, 0, 0, 'BB02', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kentang Medians', 'kg', 0, 0, 0, 'BB03', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Jagung', 'kg', 0, 0, 0, 'BB04', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Wortel', 'kg', 0, 0, 0, 'BB05', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Buncis', 'kg', 0, 0, 0, 'BB06', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kacang Polong', 'kg', 0, 0, 0, 'BB07', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Brokoli', 'kg', 0, 0, 0, 'BB08', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kembang Kol', 'kg', 0, 0, 0, 'BB09', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kentang Ventury', 'kg', 0, 0, 0, 'BB10', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Kemas', 'Plastik uk 30x45', 'pcs', 40939, 0, 0, 'BK01', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik uk 20x35', 'pcs', 149, 0, 0, 'BK02', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik uk 15x25', 'pcs', 0, 0, 0, 'BK03', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik uk 90x120 (trashbag)', 'pcs', 32, 0, 0, 'BK04', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Cheesy Potato Nugget 1kg', 'pcs', 45, 0, 0, 'BK05', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Cheesy Potato Nugget 250gr', 'pcs', 95, 0, 0, 'BK06', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Cheesy Potato Nugget 500gr (sablon)', 'pcs', 65, 0, 0, 'BK07', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Hashbrown 1kg', 'pcs', 180, 0, 0, 'BK08', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Hashbrown 250gr', 'pcs', 200, 0, 0, 'BK09', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Hashbrown 500gr', 'pcs', 0, 0, 0, 'BK10', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Jagung 500gr', 'pcs', 0, 0, 0, 'BK11', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Jagung 1kg', 'pcs', 480, 0, 0, 'BK12', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mashed Potato 1kg', 'pcs', 0, 0, 0, 'BK13', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mashed Potato 250gr', 'pcs', 66, 0, 0, 'BK14', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mashed Potato 500gr (sablon)', 'pcs', 0, 0, 0, 'BK15', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mix Vegetables 1kg', 'pcs', 45, 0, 0, 'BK16', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mix Vegetables 500gr', 'pcs', 47, 0, 0, 'BK17', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Polos 500gr', 'pcs', 22, 0, 0, 'BK18', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Polos 1kg', 'pcs', 215, 0, 0, 'BK19', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Polos 2kg', 'pcs', 4160, 0, 0, 'BK20', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Rendang Wedges 500gr (sablon)', 'pcs', 0, 0, 0, 'BK21', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Rendang Wedges 1kg', 'pcs', 0, 0, 0, 'BK22', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Fries 1kg', 'pcs', 0, 0, 0, 'BK23', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Fries 250gr', 'pcs', 0, 0, 0, 'BK24', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Fries 500gr', 'pcs', 0, 0, 0, 'BK25', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Wedges 1kg', 'pcs', 0, 0, 0, 'BK26', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Wedges 250gr', 'pcs', 0, 0, 0, 'BK27', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Wedges 500gr', 'pcs', 256, 0, 0, 'BK28', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Shoestring 1kg', 'pcs', 71, 0, 0, 'BK29', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Shoestring 500gr', 'pcs', 61, 0, 0, 'BK30', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Straightcut 1kg', 'pcs', 0, 0, 0, 'BK31', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Straightcut 500gr', 'pcs', 87, 0, 0, 'BK32', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Tulisan Hitam 1kg', 'pcs', 0, 0, 0, 'BK33', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Waffle Fries 500gr (sablon)', 'pcs', 396, 0, 0, 'BK34', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Waffle Fries 1kg', 'pcs', 0, 0, 0, 'BK35', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 1kg', 'pcs', 20, 0, 0, 'BK36', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 250gr', 'pcs', 57, 0, 0, 'BK37', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 500gr', 'pcs', 234, 0, 0, 'BK38', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 2kg', 'pcs', 40, 0, 0, 'BK39', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Stiker Potato Balls', 'pcs', 0, 0, 0, 'BK40', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Stiker Potato Sticks', 'pcs', 0, 0, 0, 'BK41', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Kardus Polos', 'pcs', 95, 0, 0, 'BK42', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Kardus Sablon', 'pcs', -35, 0, 0, 'BK43', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Lakban', 'roll', 3, 0, 0, 'BK44', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'plastik 60 x 100', 'pcs', 0, 0, 0, 'BK45', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Southmount 1kg', 'pcs', 560, 0, 0, 'BK46', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Southmount 2kg', 'pcs', 411, 0, 0, 'BK47', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'plastik 40 x 60', 'pcs', 0, 0, 0, 'BK48', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Crinkle Cut 1kg', 'pcs', 19, 0, 0, 'BK49', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Penolong', 'Masker', 'pcs', -58, 0, 0, 'BP01', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sarung Tangan Plastik', 'pcs', -275, 0, 0, 'BP02', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sarung Tangan Latex', 'pcs', 0, 0, 0, 'BP03', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Nurse Cap', 'pcs', -46, 0, 0, 'BP04', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Spidol', 'pcs', 12, 0, 0, 'BP05', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sabun Cuci Piring', 'ml', 570, 0, 0, 'BP06', 'Kebersihan & Sanitasi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sabun Lantai', 'pcs', 0, 0, 0, 'BP07', 'Kebersihan & Sanitasi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Tambahan Pangan', 'Minyak Sawit', 'liter', 0, 0, 0, 'BTP01', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Minyak Canola', 'liter', 5, 0, 0, 'BTP02', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Dextrose Monohydrate', 'gr', 2150, 0, 0, 'BTP03', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Malto Dextrin', 'gr', 18700, 0, 0, 'BTP04', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Citric Acid', 'gr', 24645, 0, 0, 'BTP05', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Garam', 'gr', 4600, 0, 0, 'BTP06', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Knorr', 'gr', 7710, 0, 0, 'BTP07', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Beras', 'gr', 54800, 0, 0, 'BTP08', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Terigu', 'gr', 0, 0, 0, 'BTP09', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Jagung', 'gr', 3540, 0, 0, 'BTP10', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Kentang', 'gr', 2610, 0, 0, 'BTP11', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Bawang Putih Bubuk / Garlic Powder', 'gr', 28565, 0, 0, 'BTP12', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Roasted Garlic', 'gr', 1000, 0, 0, 'BTP13', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Lada Putih', 'gr', 2765, 0, 0, 'BTP14', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Bumbu Rendang Indofood', 'pcs', 27, 0, 0, 'BTP15', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Keju Mozzarella', 'gr', 0, 0, 0, 'BTP16', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Keju Cheddar', 'gr', 6500, 0, 0, 'BTP17', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Polenta', 'gr', 0, 0, 0, 'BTP18', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Baking Powder', 'gr', 5530, 0, 0, 'BTP19', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Ragi', 'gr', 0, 0, 0, 'BTP20', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Chili Powder', 'gr', 0, 0, 0, 'BTP21', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Paprika Bubuk', 'gr', 15430, 0, 0, 'BTP22', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Pewarna Merah', 'ml', 0, 0, 0, 'BTP23', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Maizena', 'gr', 52950, 0, 0, 'BTP24', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tapioka', 'gr', 1000, 0, 0, 'BTP25', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan')
)
-- 3) Update item yang ketemu berdasarkan nama + kategori.
update public.items i
set
  unit = s.unit,
  min_stock = s.min_stock,
  pcs_per_dus = s.pcs_per_dus,
  item_code = coalesce(nullif(i.item_code,''), nullif(s.item_code,'')),
  lokasi = s.lokasi,
  supplier = s.supplier,
  qc_status = s.qc_status,
  deskripsi = s.deskripsi,
  archived = false
from source_items s
where lower(trim(i.name)) = lower(trim(s.name))
  and lower(trim(i.category)) = lower(trim(s.category));

with source_items(category, name, unit, starting_stock, min_stock, pcs_per_dus, item_code, lokasi, supplier, qc_status, deskripsi) as (
  values
('Produk Akhir', 'Wedges Plain 500gr', 'pcs', 0, 0, 20, 'PA01', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Wedges Plain 1kg', 'pcs', 0, 0, 10, 'PA02', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Wedges Plain 2kg', 'pcs', 0, 0, 5, 'PA03', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Waffle Seasoned Fries 500gr', 'pcs', 0, 0, 20, 'PA04', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Waffle Seasoned Fries 1kg', 'pcs', 0, 0, 10, 'PA05', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Waffle Seasoned Fries 2kg', 'pcs', 0, 0, 5, 'PA06', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Rendang Seasoned Wedges 500gr', 'pcs', 11, 0, 20, 'PA07', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Rendang Seasoned Wedges 1kg', 'pcs', 0, 0, 10, 'PA08', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Rendang Seasoned Wedges 2kg', 'pcs', 0, 0, 5, 'PA09', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 500gr', 'pcs', 37, 0, 20, 'PA10', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 1kg', 'pcs', -51, 0, 10, 'PA11', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 2kg', 'pcs', 0, 0, 5, 'PA12', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Cheesy Potato Nuggets 500gr', 'pcs', 0, 0, 20, 'PA13', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Cheesy Potato Nuggets 1kg', 'pcs', 11, 0, 10, 'PA14', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Cheesy Potato Nuggets 2kg', 'pcs', 0, 0, 5, 'PA15', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mozzarella Potato Sticks 10pcs', 'pcs', 0, 0, 0, 'PA16', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mozzarella Potato Balls 10pcs', 'pcs', 0, 0, 0, 'PA17', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mixed Vegetables 4 Ways 1kg', 'pcs', 4, 0, 10, 'PA18', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mixed Vegetables 3 Ways 1kg', 'pcs', 5, 0, 10, 'PA19', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mixed Capcay 1kg', 'pcs', 0, 0, 10, 'PA20', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Jagung Manis Pipil 1kg', 'pcs', 12, 0, 10, 'PA21', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Jagung', 'kg', 0, 0, 0, 'PA22', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Wortel', 'kg', 0, 0, 0, 'PA23', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Buncis', 'kg', 0, 0, 0, 'PA24', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Kacang Polong', 'kg', 0, 0, 0, 'PA25', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Crinkle Cut 500gr', 'pcs', 0, 0, 20, 'PA26', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Crinkle Cut 1kg', 'pcs', 0, 0, 10, 'PA27', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Crinkle Cut 2kg', 'pcs', 0, 0, 5, 'PA28', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 500gr', 'pcs', 0, 0, 20, 'PA29', 'Freezer Produk Jadi - 500gr', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 1kg ( Sablon )', 'pcs', 30, 0, 10, 'PA30', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 2kg', 'pcs', 4, 0, 5, 'PA31', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Sweet Chopped Carrots', 'pcs', 0, 0, 0, 'PA32', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Shoestring Battercoated 2kg', 'kg', 0, 0, 5, 'PA33', 'Freezer Produk Jadi - 2kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Baby Potato', 'pcs', 0, 0, 0, 'PA34', 'Freezer Produk Jadi', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Edamame 1kg', 'pcs', 0, 0, 10, 'PA35', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Seasoned Wedges 1kg ( Polos )', 'pcs', 36, 0, 10, '', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Produk Akhir', 'Mashed Potato 1kg ( Sablon ) GB', 'pcs', 0, 0, 10, '', 'Freezer Produk Jadi - 1kg', 'Produksi Internal', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Produk Akhir'),
('Bahan Baku', 'Kentang Atlantik', 'kg', 0, 0, 0, 'BB01', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kentang Granola', 'kg', 0, 0, 0, 'BB02', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kentang Medians', 'kg', 0, 0, 0, 'BB03', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Jagung', 'kg', 0, 0, 0, 'BB04', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Wortel', 'kg', 0, 0, 0, 'BB05', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Buncis', 'kg', 0, 0, 0, 'BB06', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kacang Polong', 'kg', 0, 0, 0, 'BB07', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Brokoli', 'kg', 0, 0, 0, 'BB08', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kembang Kol', 'kg', 0, 0, 0, 'BB09', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Baku', 'Kentang Ventury', 'kg', 0, 0, 0, 'BB10', 'Freezer Bahan Baku', 'Supplier Bahan Baku', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Baku'),
('Bahan Kemas', 'Plastik uk 30x45', 'pcs', 40939, 0, 0, 'BK01', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik uk 20x35', 'pcs', 149, 0, 0, 'BK02', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik uk 15x25', 'pcs', 0, 0, 0, 'BK03', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik uk 90x120 (trashbag)', 'pcs', 32, 0, 0, 'BK04', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Cheesy Potato Nugget 1kg', 'pcs', 45, 0, 0, 'BK05', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Cheesy Potato Nugget 250gr', 'pcs', 95, 0, 0, 'BK06', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Cheesy Potato Nugget 500gr (sablon)', 'pcs', 65, 0, 0, 'BK07', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Hashbrown 1kg', 'pcs', 180, 0, 0, 'BK08', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Hashbrown 250gr', 'pcs', 200, 0, 0, 'BK09', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Hashbrown 500gr', 'pcs', 0, 0, 0, 'BK10', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Jagung 500gr', 'pcs', 0, 0, 0, 'BK11', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Jagung 1kg', 'pcs', 480, 0, 0, 'BK12', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mashed Potato 1kg', 'pcs', 0, 0, 0, 'BK13', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mashed Potato 250gr', 'pcs', 66, 0, 0, 'BK14', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mashed Potato 500gr (sablon)', 'pcs', 0, 0, 0, 'BK15', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mix Vegetables 1kg', 'pcs', 45, 0, 0, 'BK16', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Mix Vegetables 500gr', 'pcs', 47, 0, 0, 'BK17', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Polos 500gr', 'pcs', 22, 0, 0, 'BK18', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Polos 1kg', 'pcs', 215, 0, 0, 'BK19', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Polos 2kg', 'pcs', 4160, 0, 0, 'BK20', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Rendang Wedges 500gr (sablon)', 'pcs', 0, 0, 0, 'BK21', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Rendang Wedges 1kg', 'pcs', 0, 0, 0, 'BK22', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Fries 1kg', 'pcs', 0, 0, 0, 'BK23', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Fries 250gr', 'pcs', 0, 0, 0, 'BK24', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Fries 500gr', 'pcs', 0, 0, 0, 'BK25', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Wedges 1kg', 'pcs', 0, 0, 0, 'BK26', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Wedges 250gr', 'pcs', 0, 0, 0, 'BK27', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Seasoned Wedges 500gr', 'pcs', 256, 0, 0, 'BK28', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Shoestring 1kg', 'pcs', 71, 0, 0, 'BK29', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Shoestring 500gr', 'pcs', 61, 0, 0, 'BK30', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Straightcut 1kg', 'pcs', 0, 0, 0, 'BK31', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Straightcut 500gr', 'pcs', 87, 0, 0, 'BK32', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Tulisan Hitam 1kg', 'pcs', 0, 0, 0, 'BK33', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Waffle Fries 500gr (sablon)', 'pcs', 396, 0, 0, 'BK34', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Waffle Fries 1kg', 'pcs', 0, 0, 0, 'BK35', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 1kg', 'pcs', 20, 0, 0, 'BK36', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 250gr', 'pcs', 57, 0, 0, 'BK37', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 500gr', 'pcs', 234, 0, 0, 'BK38', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Wedges Plain 2kg', 'pcs', 40, 0, 0, 'BK39', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Stiker Potato Balls', 'pcs', 0, 0, 0, 'BK40', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Stiker Potato Sticks', 'pcs', 0, 0, 0, 'BK41', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Kardus Polos', 'pcs', 95, 0, 0, 'BK42', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Kardus Sablon', 'pcs', -35, 0, 0, 'BK43', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Lakban', 'roll', 3, 0, 0, 'BK44', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'plastik 60 x 100', 'pcs', 0, 0, 0, 'BK45', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Southmount 1kg', 'pcs', 560, 0, 0, 'BK46', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Southmount 2kg', 'pcs', 411, 0, 0, 'BK47', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'plastik 40 x 60', 'pcs', 0, 0, 0, 'BK48', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Kemas', 'Plastik Crinkle Cut 1kg', 'pcs', 19, 0, 0, 'BK49', 'Gudang Bahan Kemas', 'Supplier Kemasan', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Kemas'),
('Bahan Penolong', 'Masker', 'pcs', -58, 0, 0, 'BP01', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sarung Tangan Plastik', 'pcs', -275, 0, 0, 'BP02', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sarung Tangan Latex', 'pcs', 0, 0, 0, 'BP03', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Nurse Cap', 'pcs', -46, 0, 0, 'BP04', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Spidol', 'pcs', 12, 0, 0, 'BP05', 'Perlengkapan Produksi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sabun Cuci Piring', 'ml', 570, 0, 0, 'BP06', 'Kebersihan & Sanitasi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Penolong', 'Sabun Lantai', 'pcs', 0, 0, 0, 'BP07', 'Kebersihan & Sanitasi', 'Supplier Bahan Penolong', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Penolong'),
('Bahan Tambahan Pangan', 'Minyak Sawit', 'liter', 0, 0, 0, 'BTP01', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Minyak Canola', 'liter', 5, 0, 0, 'BTP02', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Dextrose Monohydrate', 'gr', 2150, 0, 0, 'BTP03', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Malto Dextrin', 'gr', 18700, 0, 0, 'BTP04', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Citric Acid', 'gr', 24645, 0, 0, 'BTP05', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Garam', 'gr', 4600, 0, 0, 'BTP06', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Knorr', 'gr', 7710, 0, 0, 'BTP07', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Beras', 'gr', 54800, 0, 0, 'BTP08', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Terigu', 'gr', 0, 0, 0, 'BTP09', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Jagung', 'gr', 3540, 0, 0, 'BTP10', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tepung Kentang', 'gr', 2610, 0, 0, 'BTP11', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Bawang Putih Bubuk / Garlic Powder', 'gr', 28565, 0, 0, 'BTP12', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Roasted Garlic', 'gr', 1000, 0, 0, 'BTP13', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Lada Putih', 'gr', 2765, 0, 0, 'BTP14', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Bumbu Rendang Indofood', 'pcs', 27, 0, 0, 'BTP15', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Keju Mozzarella', 'gr', 0, 0, 0, 'BTP16', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Keju Cheddar', 'gr', 6500, 0, 0, 'BTP17', 'Chiller / Gudang BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Polenta', 'gr', 0, 0, 0, 'BTP18', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Baking Powder', 'gr', 5530, 0, 0, 'BTP19', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Ragi', 'gr', 0, 0, 0, 'BTP20', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Chili Powder', 'gr', 0, 0, 0, 'BTP21', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Paprika Bubuk', 'gr', 15430, 0, 0, 'BTP22', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Pewarna Merah', 'ml', 0, 0, 0, 'BTP23', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Maizena', 'gr', 52950, 0, 0, 'BTP24', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan'),
('Bahan Tambahan Pangan', 'Tapioka', 'gr', 1000, 0, 0, 'BTP25', 'Gudang Bumbu & BTP', 'Supplier Bumbu/BTP', 'OK', 'Import KStok HF Maret Pabrik 2026 - KS Bahan Tambahan Pangan')
)
-- 4) Tambah item dari file KStok yang belum ada.
insert into public.items (category, name, unit, starting_stock, min_stock, pcs_per_dus, item_code, physical_stock, archived, lokasi, supplier, qc_status, deskripsi)
select
  s.category,
  s.name,
  s.unit,
  s.starting_stock,
  s.min_stock,
  s.pcs_per_dus,
  nullif(s.item_code,''),
  null,
  false,
  s.lokasi,
  s.supplier,
  s.qc_status,
  s.deskripsi
from source_items s
where not exists (
  select 1
  from public.items i
  where (nullif(s.item_code,'') is not null and nullif(i.item_code,'') = nullif(s.item_code,''))
     or (lower(trim(i.name)) = lower(trim(s.name)) and lower(trim(i.category)) = lower(trim(s.category)))
);

notify pgrst, 'reload schema';

-- Cek hasil aktif setelah sync:
select category, count(*) as jumlah_item_aktif
from public.items
where coalesce(archived,false) = false
group by category
order by category;
